stages:
  - build
  - test
  - deploy
build website:
  stage: build
  image: node
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - ls -ltr
  artifacts:
    paths:
      - ./public

test artifact:
  stage: test
  script:
    - grep "Gatsby" ./public/index.html
#    - grep "daahhga" ./public/index.html

test website:
  stage: test
  image: node
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 30
    - curl http://localhost:9000


# surge.sh is platform used to deploy the static code websites in serverless architecture
deploy website:
  stage: deploy
  image: node
  script:
    - npm install --global surge
    - surge --project ./public --domain facezoneinsta.surge.sh