stages:
  - build
  - test
build website:
  stage: build
  image: node
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - ls -ltr
  artifacts:
    paths:
      - ./public

test artifact:
  stage: test
  script:
    - grep "Gatsby" ./public/index.html
#    - grep "daahhga" ./public/index.html

test website:
  stage: test
  image: node
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 30
    - curl http://localhost:9000