build website:
  image: node
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - ls -ltr
  artifacts:
    paths:
      - ./public

test artifact:
  script:
    - grep "Gatsby" ./public/index.html
    - grep "daahhga"  ./public/index.html